# Generated by Django 5.1.6 on 2025-04-18 20:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_pokemoncard_userpokemon'),
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the trade was completed')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='completed', help_text='Final status of the trade', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Trade histories',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.RemoveField(
            model_name='tradeitem',
            name='pokemon_offered',
        ),
        migrations.RemoveField(
            model_name='tradeitem',
            name='trade',
        ),
        migrations.RemoveField(
            model_name='tradenotification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='tradenotification',
            name='trade',
        ),
        migrations.RemoveField(
            model_name='tradeoffer',
            name='receiver',
        ),
        migrations.AddField(
            model_name='tradenotification',
            name='notification_type',
            field=models.CharField(choices=[('offer_received', 'New Trade Offer'), ('offer_accepted', 'Trade Accepted'), ('offer_declined', 'Trade Declined'), ('trade_completed', 'Trade Completed'), ('trade_cancelled', 'Trade Cancelled')], default='offer_received', help_text='Type of notification', max_length=20),
        ),
        migrations.AddField(
            model_name='tradenotification',
            name='trade_offer',
            field=models.ForeignKey(blank=True, help_text='Related trade offer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='trading.tradeoffer'),
        ),
        migrations.AddField(
            model_name='tradeoffer',
            name='offered_pokemon',
            field=models.ManyToManyField(help_text='Pokémon being offered by the sender', related_name='offered_in_trades', to='pokemon.userpokemon'),
        ),
        migrations.AddField(
            model_name='tradeoffer',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='User who received the trade offer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_trade_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tradeoffer',
            name='requested_pokemon',
            field=models.ManyToManyField(help_text='Pokémon being requested from the recipient', related_name='requested_in_trades', to='pokemon.userpokemon'),
        ),
        migrations.AlterField(
            model_name='tradenotification',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Whether the user has read this notification'),
        ),
        migrations.AlterField(
            model_name='tradenotification',
            name='user',
            field=models.ForeignKey(help_text='User who should receive the notification', on_delete=django.db.models.deletion.CASCADE, related_name='trade_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tradeoffer',
            name='message',
            field=models.TextField(blank=True, help_text='Optional message from the sender'),
        ),
        migrations.AlterField(
            model_name='tradeoffer',
            name='sender',
            field=models.ForeignKey(help_text='User who initiated the trade', on_delete=django.db.models.deletion.CASCADE, related_name='sent_trade_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tradeoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='Current status of the trade offer', max_length=20),
        ),
        migrations.AddIndex(
            model_name='tradenotification',
            index=models.Index(fields=['user', 'is_read'], name='trading_tra_user_id_70604e_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeoffer',
            index=models.Index(fields=['sender', 'status'], name='trading_tra_sender__32ae95_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeoffer',
            index=models.Index(fields=['recipient', 'status'], name='trading_tra_recipie_37b08a_idx'),
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='trade_offer',
            field=models.OneToOneField(help_text='The original trade offer', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='trading.tradeoffer'),
        ),
        migrations.DeleteModel(
            name='TradeItem',
        ),
    ]
