# Generated by Django 5.1.6 on 2025-04-22 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('pokemon', '0002_pokemoncard_userpokemon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplacelisting',
            name='description',
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to='pokemon.userpokemon'),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='marketplacelisting',
            index=models.Index(fields=['status'], name='marketplace_status_91fad9_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacelisting',
            index=models.Index(fields=['price'], name='marketplace_price_e7704d_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacelisting',
            index=models.Index(fields=['created_at'], name='marketplace_created_d8ae55_idx'),
        ),
    ]
