# Generated by Django 5.1.6 on 2025-03-31 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pokemon_id', models.IntegerField(unique=True)),
                ('image_url', models.URLField()),
                ('primary_type', models.CharField(choices=[('normal', 'Normal'), ('fire', 'Fire'), ('water', 'Water'), ('grass', 'Grass'), ('electric', 'Electric'), ('ice', 'Ice'), ('fighting', 'Fighting'), ('poison', 'Poison'), ('ground', 'Ground'), ('flying', 'Flying'), ('psychic', 'Psychic'), ('bug', 'Bug'), ('rock', 'Rock'), ('ghost', 'Ghost'), ('dragon', 'Dragon'), ('dark', 'Dark'), ('steel', 'Steel'), ('fairy', 'Fairy')], max_length=20)),
                ('secondary_type', models.CharField(blank=True, choices=[('normal', 'Normal'), ('fire', 'Fire'), ('water', 'Water'), ('grass', 'Grass'), ('electric', 'Electric'), ('ice', 'Ice'), ('fighting', 'Fighting'), ('poison', 'Poison'), ('ground', 'Ground'), ('flying', 'Flying'), ('psychic', 'Psychic'), ('bug', 'Bug'), ('rock', 'Rock'), ('ghost', 'Ghost'), ('dragon', 'Dragon'), ('dark', 'Dark'), ('steel', 'Steel'), ('fairy', 'Fairy')], max_length=20, null=True)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('ultra_rare', 'Ultra Rare'), ('legendary', 'Legendary')], max_length=20)),
                ('base_value', models.IntegerField(default=100)),
                ('description', models.TextField(blank=True)),
                ('height', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_date', models.DateTimeField(auto_now_add=True)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('favorite', models.BooleanField(default=False)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acquired_date'],
                'unique_together': {('user', 'pokemon')},
            },
        ),
    ]
