# Generated by Django 5.1.6 on 2025-04-04 20:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('set_name', models.CharField(max_length=100)),
                ('set_code', models.CharField(max_length=20)),
                ('rarity', models.CharField(blank=True, max_length=50)),
                ('image_url', models.URLField()),
                ('small_image_url', models.URLField(blank=True)),
                ('large_image_url', models.URLField(blank=True)),
                ('card_market_url', models.URLField(blank=True)),
                ('tcgplayer_url', models.URLField(blank=True)),
                ('cardmarket_url', models.URLField(blank=True)),
                ('cardmarket_prices', models.JSONField(blank=True, null=True)),
                ('tcgplayer_prices', models.JSONField(blank=True, null=True)),
                ('types', models.JSONField(blank=True, null=True)),
                ('weaknesses', models.JSONField(blank=True, null=True)),
                ('resistances', models.JSONField(blank=True, null=True)),
                ('retreat_cost', models.JSONField(blank=True, null=True)),
                ('converted_retreat_cost', models.IntegerField(blank=True, null=True)),
                ('hp', models.CharField(blank=True, max_length=10)),
                ('artist', models.CharField(blank=True, max_length=100)),
                ('flavor_text', models.TextField(blank=True)),
                ('national_pokedex_numbers', models.JSONField(blank=True, null=True)),
                ('legalities', models.JSONField(blank=True, null=True)),
                ('regulation_mark', models.CharField(blank=True, max_length=10)),
                ('base_value', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'set_name'],
            },
        ),
        migrations.CreateModel(
            name='UserPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_for_sale', models.BooleanField(default=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('acquired_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemoncard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acquired_date'],
                'unique_together': {('user', 'card')},
            },
        ),
    ]
